#cloud-config
groups:
  - ubuntu: [root,sys]
  - docker
  - bot

users:
  - default
  - name: keeper
    gecos: keeper
    shell: /bin/bash
    primary_group: bot
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    lock_passwd: false

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - chrony
  - docker.io
  - docker-compose

ntp:
  enabled: true
  ntp_client: chrony
  servers:
    - ${ntp_server}

runcmd:
  - systemctl stop snapd && systemctl disable snapd
  - git clone https://github.com/0x1d/drift-keeper /app/bot
  - cp -rT /transfer /app/bot && rm -rf /transfer
  - chown -R keeper:bot /app/bot
  - cd /app/bot && sudo -u keeper -g bot -- docker-compose up -d

write_files:
  - path: /transfer/.env
    encoding: b64
    owner: root:root
    permissions: '0750'
    content: ${env_file}
  - path: /transfer/config.yaml
    encoding: b64
    owner: root:root
    permissions: '0750'
    content: ${config_file}
  - path: /transfer/docker-compose.yaml
    encoding: b64
    owner: root:root
    permissions: '0750'
    content: ${docker_compose_file}
    