{
 "title": "Drift Keeper",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Collateral",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_collateral", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Profit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "total_collateral", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Unrealized PNL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "unrealized_pnl", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SOL Balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sol_balance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SOL Balance in USDC",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sol_usdc_balance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "USDC Balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "usdc_balance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Activity",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "unrealized_pnl", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SOL Change",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "sol_balance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SOL Change in USDC",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "sol_usdc_balance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "USDC Change",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    { "expr": "usdc_balance", "legendFormat": "__auto" }
   ]
  },
  { "title": "Wallet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "SOL Balance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "targets": [
    { "expr": "sol_balance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SOL Balance in USDC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
   "targets": [
    { "expr": "sol_usdc_balance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "USDC Balance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
   "targets": [
    { "expr": "usdc_balance", "legendFormat": "__auto" }
   ]
  },
  { "title": "Profit & Loss", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Total Collateral",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "total_collateral", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Unrealized PNL",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "unrealized_pnl", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SOL Price",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "sol_price", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Order Matching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Successful Fills Total",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
     "targets": [
      { "expr": "successful_fills_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Attempted Fills Total",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 35 },
     "targets": [
      { "expr": "attempted_fills_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Attempted Fill Duration",
     "type": "histogram",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(try_fill_duration_histogram_sum[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SDK Call Duration",
     "type": "histogram",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(sdk_call_duration_histogram_sum[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}